[project]
name = "quiz_server"
version = "1.0.0"
description = ""
authors = [{ name = "Benjamin Bowles" }]
dependencies = ["flask", "python-dotenv", "pandas"]


[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
