name: Greet new contributors

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hi @${{ github.event.issue.user.login }}, thanks for opening an issue! We appreciate your contribution. Please make sure you follow the issue template and provide all necessary details.
          pr-message: |
            Hi @${{ github.event.pull_request.user.login }}, thanks for opening a pull request! We appreciate your contribution. Please make sure you follow the PR template and provide all necessary details.
